Feature/eslint settings
kirillstepanchuk/worker-manager pull request #2
Opened 2021-12-12 23:18 UTC by kirillstepanchuk

configured eslint and rewrote code with eslint rules

2021-12-13 12:30 UTC, vik-buchinski requested changes

2021-12-13 12:30 UTC, vik-buchinski commented on app-backend/package.json
> +		"eslint-config-airbnb": "^19.0.2",
please, read about  dependencies and devDependencies and fix deps in your package.json

2021-12-13 12:30 UTC, vik-buchinski commented on app-frontend/package.json
> +    "start": "webpack-dev-server --config ./webpacks/webpack.dev.js --open --hot",
👍  for the '--config ./webpacks/webpack.dev.js '

2021-12-13 12:30 UTC, vik-buchinski commented on app-frontend/package.json
> +    "terser-webpack-plugin": "^5.2.5",
the same comment about deps here

2021-12-13 12:30 UTC, vik-buchinski commented on app-frontend/src/components/App/index.js
> +// export { default } from './App';
barrel file with just a comment?
You shouldn't commit commented out code at all

2021-12-13 12:30 UTC, vik-buchinski commented on app-frontend/src/store/sagas/worker.js
> +      `${API_URL}/workers?pageNumber=${payload.page}&positionType=${payload.filterParameters.positionType}&sortingType=${payload.filterParameters.sortingType}&time=${payload.filterParameters.time}`,
here is the way how to fix issue with long string:
https://github.com/axios/axios#browser

just build query params in the appropriate way.

2021-12-13 12:30 UTC, vik-buchinski commented on app-frontend/webpacks/webpack.common.js
> -    //     configFile: './.eslintrc.js',
what the reason for committing commented out code here?

2021-12-14 13:46 UTC, vik-buchinski approved these changes

2021-12-16 08:54 UTC, kirillstepanchuk commented
configured eslint and rewrote code with eslint rules

2021-12-21 08:52 UTC, merged